# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
#   r estart: always
    ports:
      - 3306:3306

    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: luiza.2014
    volumes:
      - microservices_mahhaus:/var/lib/mysql

volumes:
  microservices_mahhaus:
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080